# Generated by Django 2.2.13 on 2022-12-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personal', 'personal'), ('shopping', 'shopping'), ('wishlist', 'wishlist'), ('work', 'work')], default='personal', max_length=20)),
                ('topic', models.CharField(max_length=225)),
                ('desciption', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
