# Generated by Django 2.2.13 on 2022-12-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='task_user',
        ),
    ]
